// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SACA_Infra.Context;

#nullable disable

namespace SACA_Infra.Migrations
{
    [DbContext(typeof(SACA_Context))]
    [Migration("20250422160904_update-contest-and-account-table")]
    partial class updatecontestandaccounttable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SACA_Infra.Models.account_notification", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Thí sinh");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("notification_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Thông báo");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("account_id");

                    b.HasIndex("notification_id");

                    b.ToTable("account_notification", t =>
                        {
                            t.HasComment("Thông báo theo tài khoản");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.best_submission", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("frozen_score")
                        .HasColumnType("double");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("number_of_attempts")
                        .HasColumnType("int");

                    b.Property<string>("problem_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("problem_submission_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("running_memory")
                        .HasColumnType("double");

                    b.Property<double>("running_time")
                        .HasColumnType("double");

                    b.Property<double>("score")
                        .HasColumnType("double");

                    b.Property<DateTime>("submited_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("problem_id");

                    b.HasIndex("problem_submission_id");

                    b.HasIndex("user_id");

                    b.ToTable("best_submissions");
                });

            modelBuilder.Entity("SACA_Infra.Models.contest", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("class_code")
                        .HasColumnType("longtext")
                        .HasComment("Lớp học");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Mã cuộc thi");

                    b.Property<int>("contest_type")
                        .HasColumnType("int")
                        .HasComment("Loại cuộc thi");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext")
                        .HasComment("Mô tả");

                    b.Property<double>("duration")
                        .HasColumnType("double")
                        .HasComment("Thời hạn");

                    b.Property<int>("duration_time_unit")
                        .HasColumnType("int")
                        .HasComment("Đơn vị tính thời hạn");

                    b.Property<DateTime>("end_at")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian kết thúc");

                    b.Property<string>("fileid")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("grading_type")
                        .HasColumnType("int")
                        .HasComment("Cách chấm điểm");

                    b.Property<bool>("is_frozen")
                        .HasColumnType("tinyint(1)")
                        .HasComment("Đóng băng");

                    b.Property<bool>("leaderboard_enabled")
                        .HasColumnType("tinyint(1)")
                        .HasComment("Bảng xếp hạng");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("penalty_time")
                        .HasColumnType("double")
                        .HasComment("Thời gian phạt");

                    b.Property<bool>("plagiarism_detection_enabled")
                        .HasColumnType("tinyint(1)")
                        .HasComment("Kiểm tra đạo văn");

                    b.Property<string>("programming_languages")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasComment("Ngôn ngữ lập trình");

                    b.Property<DateTime>("start_at")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian bắt đầu");

                    b.Property<int>("status")
                        .HasColumnType("int")
                        .HasComment("Trạng thái");

                    b.Property<string>("subject_code")
                        .HasColumnType("longtext")
                        .HasComment("Mã môn học");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Tiêu đề cuộc thi");

                    b.HasKey("id");

                    b.HasIndex("fileid");

                    b.ToTable("contest", t =>
                        {
                            t.HasComment("Cuộc thi");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.contest_participant", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Thí sinh");

                    b.Property<string>("contest_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Cuộc thi");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("invitation_email_sent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("account_id");

                    b.HasIndex("contest_id");

                    b.ToTable("contest_participant", t =>
                        {
                            t.HasComment("Thí sinh tham gia cuộc thi");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.notification", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("contest_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Id cuộc thi");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Nội dung");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("problem_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Tiêu đề thông báo");

                    b.HasKey("id");

                    b.HasIndex("contest_id");

                    b.HasIndex("problem_id")
                        .IsUnique();

                    b.ToTable("notification", t =>
                        {
                            t.HasComment("Thông báo");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.problem", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Mã câu hỏi");

                    b.Property<string>("contest_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Id cuộc thi");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("default_execution_time")
                        .HasColumnType("double")
                        .HasComment("Giới hạn thời gian chạy (ms)");

                    b.Property<double?>("default_memory_limit")
                        .HasColumnType("double")
                        .HasComment("Giới hạn bộ nhớ (Kb)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext")
                        .HasComment("Mô tả");

                    b.Property<string>("file_id")
                        .HasColumnType("varchar(255)")
                        .HasComment("Tài nguyên");

                    b.Property<int?>("max_attempts")
                        .HasColumnType("int")
                        .HasComment("Giới hạn số lần nộp bài");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("note")
                        .HasColumnType("longtext")
                        .HasComment("Ghi chú");

                    b.Property<double>("score")
                        .HasColumnType("double")
                        .HasComment("Số điểm của câu hỏi");

                    b.Property<string>("tags")
                        .HasColumnType("longtext")
                        .HasComment("Danh sách tag");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Tiêu đề câu hỏi");

                    b.HasKey("id");

                    b.HasIndex("contest_id");

                    b.HasIndex("file_id")
                        .IsUnique();

                    b.ToTable("problem", t =>
                        {
                            t.HasComment("Câu hỏi");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.problem_submission", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Người nộp");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("file_path")
                        .HasColumnType("longtext")
                        .HasComment("Đường dẫn file nộp");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("problem_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Câu hỏi");

                    b.Property<int>("programming_language")
                        .HasColumnType("int")
                        .HasComment("Loại ngôn ngữ lập trình");

                    b.Property<double>("runinng_time")
                        .HasColumnType("double");

                    b.Property<double>("running_memory")
                        .HasColumnType("double");

                    b.Property<double>("scrore")
                        .HasColumnType("double");

                    b.Property<string>("source_code")
                        .HasColumnType("longtext")
                        .HasComment("Source code");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("submitted_at")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian nộp bài");

                    b.HasKey("id");

                    b.HasIndex("account_id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_submission", t =>
                        {
                            t.HasComment("Bài nộp");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.saca_file", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("extension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("length")
                        .HasColumnType("bigint");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("parent_id")
                        .HasColumnType("longtext");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("saca_file");
                });

            modelBuilder.Entity("SACA_Infra.Models.submission_grading", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("actual_output")
                        .HasColumnType("longtext");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("judge0_token")
                        .HasColumnType("longtext");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("problem_submission_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("runinng_time")
                        .HasColumnType("double");

                    b.Property<double>("running_memory")
                        .HasColumnType("double");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("test_case_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("problem_submission_id");

                    b.HasIndex("test_case_id");

                    b.ToTable("submission_grading");
                });

            modelBuilder.Entity("SACA_Infra.Models.sys_account", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Email");

                    b.Property<int>("failed_count")
                        .HasColumnType("int")
                        .HasComment("Số lần đăng nhập thất bại");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Tên đầy đủ");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("datetime(6)")
                        .HasComment("Lần đăng nhập gần nhất");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Mật khẩu mã hóa");

                    b.Property<string>("password_salt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Mã mật khẩu");

                    b.Property<string>("role_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("roll_number")
                        .HasColumnType("longtext")
                        .HasComment("Mã số sinh viên");

                    b.Property<int>("status")
                        .HasColumnType("int")
                        .HasComment("Trạng thái account");

                    b.Property<string>("sys_generated_password")
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Tên đăng nhập");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("sys_account", t =>
                        {
                            t.HasComment("Tài khoản");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.sys_role", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("sys_role", t =>
                        {
                            t.HasComment("phan quyen");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.test_case", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Mã test case");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext")
                        .HasComment("Mô tả");

                    b.Property<double?>("execution_time")
                        .HasColumnType("double")
                        .HasComment("Giới hạn thời gian chạy (ms)");

                    b.Property<string>("input")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Dữ liệu nhận vào");

                    b.Property<double?>("memory_limit")
                        .HasColumnType("double")
                        .HasComment("Giới hạn bộ nhớ (Kb)");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("order")
                        .HasColumnType("int")
                        .HasComment("Thứ tự chạy test case");

                    b.Property<string>("output")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Kết quả trả ra");

                    b.Property<string>("problem_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Câu hỏi");

                    b.Property<double>("score")
                        .HasColumnType("double")
                        .HasComment("Điểm");

                    b.Property<int>("testcase_type")
                        .HasColumnType("int")
                        .HasComment("Loại test case");

                    b.HasKey("id");

                    b.HasIndex("problem_id");

                    b.ToTable("testcase", t =>
                        {
                            t.HasComment("Test case của câu hỏi");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.account_notification", b =>
                {
                    b.HasOne("SACA_Infra.Models.sys_account", "account")
                        .WithMany("notifications")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SACA_Infra.Models.notification", "notification")
                        .WithMany()
                        .HasForeignKey("notification_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");

                    b.Navigation("notification");
                });

            modelBuilder.Entity("SACA_Infra.Models.best_submission", b =>
                {
                    b.HasOne("SACA_Infra.Models.problem", "problem")
                        .WithMany("best_submissions")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SACA_Infra.Models.problem_submission", "problem_submission")
                        .WithMany()
                        .HasForeignKey("problem_submission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SACA_Infra.Models.sys_account", "sys_account")
                        .WithMany("best_submissions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("problem");

                    b.Navigation("problem_submission");

                    b.Navigation("sys_account");
                });

            modelBuilder.Entity("SACA_Infra.Models.contest", b =>
                {
                    b.HasOne("SACA_Infra.Models.saca_file", "file")
                        .WithMany()
                        .HasForeignKey("fileid");

                    b.Navigation("file");
                });

            modelBuilder.Entity("SACA_Infra.Models.contest_participant", b =>
                {
                    b.HasOne("SACA_Infra.Models.sys_account", "account")
                        .WithMany("contests")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SACA_Infra.Models.contest", "contest")
                        .WithMany("contest_participants")
                        .HasForeignKey("contest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");

                    b.Navigation("contest");
                });

            modelBuilder.Entity("SACA_Infra.Models.notification", b =>
                {
                    b.HasOne("SACA_Infra.Models.contest", "contest")
                        .WithMany("notifications")
                        .HasForeignKey("contest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SACA_Infra.Models.problem", "problem")
                        .WithOne("notification")
                        .HasForeignKey("SACA_Infra.Models.notification", "problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contest");

                    b.Navigation("problem");
                });

            modelBuilder.Entity("SACA_Infra.Models.problem", b =>
                {
                    b.HasOne("SACA_Infra.Models.contest", "contest")
                        .WithMany("problems")
                        .HasForeignKey("contest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SACA_Infra.Models.saca_file", "file")
                        .WithOne()
                        .HasForeignKey("SACA_Infra.Models.problem", "file_id");

                    b.Navigation("contest");

                    b.Navigation("file");
                });

            modelBuilder.Entity("SACA_Infra.Models.problem_submission", b =>
                {
                    b.HasOne("SACA_Infra.Models.sys_account", "submitter")
                        .WithMany("submissions")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SACA_Infra.Models.problem", "problem")
                        .WithMany("submissions")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("problem");

                    b.Navigation("submitter");
                });

            modelBuilder.Entity("SACA_Infra.Models.submission_grading", b =>
                {
                    b.HasOne("SACA_Infra.Models.problem_submission", "problem_submission")
                        .WithMany("submission_gradings")
                        .HasForeignKey("problem_submission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SACA_Infra.Models.test_case", "test_case")
                        .WithMany("submission_grading")
                        .HasForeignKey("test_case_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("problem_submission");

                    b.Navigation("test_case");
                });

            modelBuilder.Entity("SACA_Infra.Models.sys_account", b =>
                {
                    b.HasOne("SACA_Infra.Models.sys_role", "sys_role")
                        .WithMany("sys_accounts")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sys_role");
                });

            modelBuilder.Entity("SACA_Infra.Models.test_case", b =>
                {
                    b.HasOne("SACA_Infra.Models.problem", "problem")
                        .WithMany("test_cases")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("problem");
                });

            modelBuilder.Entity("SACA_Infra.Models.contest", b =>
                {
                    b.Navigation("contest_participants");

                    b.Navigation("notifications");

                    b.Navigation("problems");
                });

            modelBuilder.Entity("SACA_Infra.Models.problem", b =>
                {
                    b.Navigation("best_submissions");

                    b.Navigation("notification")
                        .IsRequired();

                    b.Navigation("submissions");

                    b.Navigation("test_cases");
                });

            modelBuilder.Entity("SACA_Infra.Models.problem_submission", b =>
                {
                    b.Navigation("submission_gradings");
                });

            modelBuilder.Entity("SACA_Infra.Models.sys_account", b =>
                {
                    b.Navigation("best_submissions");

                    b.Navigation("contests");

                    b.Navigation("notifications");

                    b.Navigation("submissions");
                });

            modelBuilder.Entity("SACA_Infra.Models.sys_role", b =>
                {
                    b.Navigation("sys_accounts");
                });

            modelBuilder.Entity("SACA_Infra.Models.test_case", b =>
                {
                    b.Navigation("submission_grading");
                });
#pragma warning restore 612, 618
        }
    }
}
