// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SACA_Infra.Context;

#nullable disable

namespace SACA_Infra.Migrations
{
    [DbContext(typeof(SACA_Context))]
    [Migration("20250131030038_init-db")]
    partial class initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SACA_Infra.Models.sys_account", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Email");

                    b.Property<int>("failed_count")
                        .HasColumnType("int")
                        .HasComment("Số lần đăng nhập thất bại");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Tên đầy đủ");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("datetime(6)")
                        .HasComment("Lần đăng nhập gần nhất");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Mật khẩu mã hóa");

                    b.Property<string>("password_salt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Mã mật khẩu");

                    b.Property<string>("role_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("status")
                        .HasColumnType("int")
                        .HasComment("Trạng thái account");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Tên đăng nhập");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("sys_account", t =>
                        {
                            t.HasComment("Tài khoản");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.sys_role", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("deleted_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("modified_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("modified_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("sys_role", t =>
                        {
                            t.HasComment("phan quyen");
                        });
                });

            modelBuilder.Entity("SACA_Infra.Models.sys_account", b =>
                {
                    b.HasOne("SACA_Infra.Models.sys_role", "sys_role")
                        .WithMany("sys_accounts")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sys_role");
                });

            modelBuilder.Entity("SACA_Infra.Models.sys_role", b =>
                {
                    b.Navigation("sys_accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
